// <auto-generated />
using System;
using LaboratorAnalize.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LaboratorAnalize.Migrations
{
    [DbContext(typeof(LaboratorAnalizeContext))]
    [Migration("20260107135555_AddBuletinSiRezultate")]
    partial class AddBuletinSiRezultate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("LaboratorAnalize.Models.BuletinAnalize", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataEliberare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observatii")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("ProgramareID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProgramareID");

                    b.ToTable("BuletinAnalize");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.PachetAnalize", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Pret")
                        .HasColumnType("decimal(6, 2)");

                    b.HasKey("ID");

                    b.ToTable("PachetAnalize");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.Pacient", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("CNP")
                        .IsRequired()
                        .HasMaxLength(13)
                        .HasColumnType("nvarchar(13)");

                    b.Property<string>("Email")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Prenume")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Telefon")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Pacient");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.Programare", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<DateTime>("DataProgramare")
                        .HasColumnType("datetime2");

                    b.Property<string>("Observatii")
                        .HasColumnType("nvarchar(max)");

                    b.Property<TimeSpan?>("OraProgramare")
                        .HasColumnType("time");

                    b.Property<int?>("PachetAnalizeID")
                        .HasColumnType("int");

                    b.Property<int?>("PacientID")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("PachetAnalizeID");

                    b.HasIndex("PacientID");

                    b.ToTable("Programare");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.ProgramareTipAnaliza", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("ProgramareID")
                        .HasColumnType("int");

                    b.Property<int>("TipAnalizaID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("ProgramareID");

                    b.HasIndex("TipAnalizaID");

                    b.ToTable("ProgramareTipAnaliza");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.RezultatAnaliza", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int?>("BuletinAnalizeID")
                        .HasColumnType("int");

                    b.Property<bool>("InLimite")
                        .HasColumnType("bit");

                    b.Property<string>("IntervalReferinta")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TipAnalizaID")
                        .HasColumnType("int");

                    b.Property<string>("Unitate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Valoare")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.HasIndex("BuletinAnalizeID");

                    b.HasIndex("TipAnalizaID");

                    b.ToTable("RezultatAnaliza");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.TipAnaliza", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Denumire")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("NecesitaNemancat")
                        .HasColumnType("bit");

                    b.Property<string>("TipProba")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("TipAnaliza");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.BuletinAnalize", b =>
                {
                    b.HasOne("LaboratorAnalize.Models.Programare", "Programare")
                        .WithMany()
                        .HasForeignKey("ProgramareID");

                    b.Navigation("Programare");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.Programare", b =>
                {
                    b.HasOne("LaboratorAnalize.Models.PachetAnalize", "PachetAnalize")
                        .WithMany("Programari")
                        .HasForeignKey("PachetAnalizeID");

                    b.HasOne("LaboratorAnalize.Models.Pacient", "Pacient")
                        .WithMany("Programari")
                        .HasForeignKey("PacientID");

                    b.Navigation("PachetAnalize");

                    b.Navigation("Pacient");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.ProgramareTipAnaliza", b =>
                {
                    b.HasOne("LaboratorAnalize.Models.Programare", "Programare")
                        .WithMany("ProgramareTipAnalize")
                        .HasForeignKey("ProgramareID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("LaboratorAnalize.Models.TipAnaliza", "TipAnaliza")
                        .WithMany("ProgramareTipAnalize")
                        .HasForeignKey("TipAnalizaID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Programare");

                    b.Navigation("TipAnaliza");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.RezultatAnaliza", b =>
                {
                    b.HasOne("LaboratorAnalize.Models.BuletinAnalize", "BuletinAnalize")
                        .WithMany("Rezultate")
                        .HasForeignKey("BuletinAnalizeID");

                    b.HasOne("LaboratorAnalize.Models.TipAnaliza", "TipAnaliza")
                        .WithMany()
                        .HasForeignKey("TipAnalizaID");

                    b.Navigation("BuletinAnalize");

                    b.Navigation("TipAnaliza");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.BuletinAnalize", b =>
                {
                    b.Navigation("Rezultate");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.PachetAnalize", b =>
                {
                    b.Navigation("Programari");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.Pacient", b =>
                {
                    b.Navigation("Programari");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.Programare", b =>
                {
                    b.Navigation("ProgramareTipAnalize");
                });

            modelBuilder.Entity("LaboratorAnalize.Models.TipAnaliza", b =>
                {
                    b.Navigation("ProgramareTipAnalize");
                });
#pragma warning restore 612, 618
        }
    }
}
